### ISSUE TITLE
Erro:  'bool' object has no attribute '__call__'

### ISSUE THREAD

**Issue by jlanio** [graup/flask-restless-security#5]
Hello, after following the steps readme.
I'm having the following error:

AttributeError
AttributeError: 'bool' object has no attribute '**call**'

**Comment by jlanio** [comment]
In research I realized that the error was due to an update of the flask-security:

So...instead of {{ current_user.is_authenticated() }}, you need to use {{ current_user.is_authenticated }}. 
Just don't include the parentheses

**Comment by graup** [comment]
Thank you! I'll test this and merge your changes. Please keep this issue open until it's fixed in master.

**Comment by graup** [comment]
I found the problem. Flask-Login [had a breaking change in 0.3](https://github.com/maxcountryman/flask-login/blob/master/CHANGES), but the most recent distributions of Flask-Security don't reflect that change or are incompatible.
I pinned Flask-Login to <0.3 for now and will update everything once the packages work together again.
Thanks again for the report!
